server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
       routes:
        - id: dipendente-service
          uri: lb://dipendente-service
          predicates:
            - Path=/app/dipendente/**

        - id: dipendente-service
          uri: lb://dipendente-service
          predicates:
            - Path=/app/dipartimento/**

        - id: dipendente-service
          uri: lb://dipendente-service
          predicates:
            - Path=/app/posizione/**

        - id: dipendente-service
          uri: lb://dipendente-service
          predicates:
            - Path=/app/auth/**

        - id: comunicazioni-service
          uri: lb://comunicazioni-service
          predicates:
            - Path=/app/comunicazione/**

        - id: comunicazioni-service
          uri: lb://comunicazioni-service
          predicates:
            - Path=/app/news/**

        - id: badge-service
          uri: lb://badge-service
          predicates:
            - Path=/app/badge/**

        - id: curriculum-service
          uri: lb://curriculum-service
          predicates:
            - Path=/app/curriculum/**

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
